application: ucbugg-flask
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /
  static_files: redirect.html
  upload: redirect.html
- url: /static
  static_dir: static
- url: /.*
  script: main.app
